# Force Yarn Berry to use classic node_modules linker (fixes Windows PnP/zip path issues with esbuild/Vite)
nodeLinker: node-modules
# optional perf improvement for Yarn 4
enableGlobalCache: true

# keep default
checksumBehavior: throw